// words.js

var words = [
    { word: 'умный', antonym: 'глупый' },
    { word: 'день', antonym: 'ночь' },
    { word: 'радушно', antonym: 'неприязненно' },
    { word: 'восход', antonym: 'закат' },
    { word: 'добро', antonym: 'зло' },
    { word: 'утро', antonym: 'вечер' },
    { word: 'мир', antonym: 'война' },
    { word: 'огонь', antonym: 'вода' },
    { word: 'труженик', antonym: 'бездельник' },
    { word: 'лето', antonym: 'зима' },
    { word: 'друг', antonym: 'враг' },
    { word: 'грусть', antonym: 'радость' },
    { word: 'болтун', antonym: 'молчун' },
    { word: 'храбрость', antonym: 'трусость' },
    { word: 'грязный', antonym: 'чистый' },
    { word: 'смелый', antonym: 'трусливый' },
    { word: 'громкий', antonym: 'тихий' },
    { word: 'широкий', antonym: 'узкий' },
    { word: 'толстый', antonym: 'тонкий' },
    { word: 'длинный', antonym: 'короткий' },
    { word: 'сильный', antonym: 'слабый' },
    { word: 'высокий', antonym: 'низкий' },
    { word: 'женственный', antonym: 'мужественный' },
    { word: 'светлый', antonym: 'темный' },
    { word: 'далекий', antonym: 'близкий' },
    { word: 'молчать', antonym: 'говорить' },
    { word: 'бежать', antonym: 'стоять' },
    { word: 'радоваться', antonym: 'огорчаться' },
    { word: 'стемнело', antonym: 'рассвело' },
    { word: 'ругать', antonym: 'хвалить' },
    { word: 'взять', antonym: 'отдать' },
    { word: 'построить', antonym: 'поломать' },
    { word: 'защитить', antonym: 'обидеть' },
    { word: 'вымокнуть', antonym: 'высохнуть' },
    { word: 'зимой', antonym: 'летом' },
    { word: 'утром', antonym: 'вечером' },
    { word: 'пешком', antonym: 'бегом' },
    { word: 'интересно', antonym: 'скучно' },
    { word: 'рано', antonym: 'поздно' },
    { word: 'впереди', antonym: 'позади' },
    { word: 'всегда', antonym: 'никогда' },
    { word: 'тут', antonym: 'там' },
    { word: 'глубоко', antonym: 'мелко' },
    // Добавьте остальные слова и антонимы сюда
  ];
  
  // Экспортируйте массив слов для использования в других файлах
  module.exports = words;